version: "2"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - ibmcloudcodeenginev1
      - codeenginev2/code_engine_v2.go
      - codeenginev2/code_engine_v2_test.go
      - codeenginev2/code_engine_v2_integration_suite_test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
