version: "2"
linters:
  enable:
    - gosec
  settings:
    gosec:
      config:
        G101:
          pattern: "(?i)passwd|pass|password|pwd|token|pw|apiKey|bearer|cred"
          ignore_entropy: false
          entropy_threshold: "80.0"
          truncate: "16"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - ibmcloudcodeenginev1
      - codeenginev2/code_engine_v2.go
      - codeenginev2/code_engine_v2_test.go
      - codeenginev2/code_engine_v2_integration_suite_test.go
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: ibmcloudcodeenginev1/ibm_cloud_code_engine_v1.go
        linters:
          - gosec
        text: "G117"
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
