language: go

node_js: '8.3'

dist: xenial

go:
- 1.12.x

env:
  global:
    - GO111MODULE=on

before_install:
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

notifications:
  email: false

before_script:
- go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
- go test `go list ./...`
- golangci-lint run
