language: go

node_js: '8.3'

dist: xenial

go:
- 1.10.x

before_install:
- nvm install 8.3
- npm install -g npm@6.x
- apt-get update
- apt-get install python
- go get -u github.com/golang/dep/cmd/dep
- go get -u gopkg.in/alecthomas/gometalinter.v2
- go get -u golang.org/x/lint/golint

install:
- dep ensure

notifications:
  email: false

script:
- go test `go list ./...`
- go test `go list ./...` -v -tags=integration
- gometalinter.v2 --errors ./...
