language: go
go: "1.18.x"
os: linux

# Only run on main (still tests PRs)
branches:
  only:
  - main


cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  # To enable semantic-release, uncomment the next 4 lines
  # - sudo apt-get update
  # - sudo apt-get install python
  # - nvm install 12
  # - npm install -g npm@6.x
  #- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

script:
  - go build ./...
  - go test ./...
  - ./test-integration.sh

# To enable semantic-release, uncomment these sections.
# before_deploy:
# - pip install --user bump2version
# - npm install @semantic-release/changelog
# - npm install @semantic-release/exec
# - npm install @semantic-release/git
# - npm install @semantic-release/github
# 
# deploy:
# - provider: script
#   script: npx semantic-release
#   skip_cleanup: true
#   on:
#     branch: master
