language: go
dist: focal

go:
- 1.23.x

# Only run on main (still tests PRs)
branches:
  only:
  - main

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - pyenv global 3.8

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - make travis-ci
