language: go
dist: focal
group: beta
version: ~> 1.0

go:
  - 1.21.x

# Only run on main (still tests PRs)
branches:
  only:
    - main

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - pyenv global 3.8

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - make travis-ci
  - ./test-integration.sh

before_deploy:
  - nvm install 20
  - npm install -g npm@9.x
  - npm install -g semantic-release
  - npm install -g @semantic-release/changelog
  - npm install -g @semantic-release/exec
  - npm install -g @semantic-release/git
  - npm install -g @semantic-release/github
  - pip install --user bump2version

deploy:
  - provider: script
    script: semantic-release
    skip_cleanup: true
    on:
      go: "1.21.x"
      branch: main
