language: go

node_js: '8.3'

dist: xenial

go:
- 1.12.x

before_install:
- apt-get update
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

install:
- dep ensure

notifications:
  email: false

before_script:
- go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
- go test `go list ./...`
- go test `go list ./...` -v -tags=integration
- golangci-lint run
