language: go

dist: xenial

go:
- 1.12.x

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

#before_script:
#- 'openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

script:
- go test `go list ./...`
#- go test `go list ./...` -tags integration
- golangci-lint run

# before_deploy:
# - pip install --user bump2version
# - npm install @semantic-release/changelog
# - npm install @semantic-release/exec
# - npm install @semantic-release/git
# - npm install @semantic-release/github
# 
# deploy:
# - provider: script
#   script: npx semantic-release
#   skip_cleanup: true
#   on:
#     branch: master
